### ISSUE TITLE
Figure out binding between Portier RP and daemon

### ISSUE THREAD

**Issue by djc** [portier/portier-broker#10]
Can likely use the `nonce` parameter from OIDC's implicit flow.

**Comment by djc** [comment]
So this means making the [AuthRequest](https://github.com/portier/portier-broker/blob/master/src/lib.rs.in#L137) require a `nonce` parameter in addition to what's there now, store it, then add it to the outgoing JWT in [create_jwt()](https://github.com/portier/portier-broker/blob/master/src/lib.rs.in#L167).

**Comment by onli** [comment]
I missed to reference this issue. I tried to do that in https://github.com/portier/portier-broker/tree/feature_nonce.

**Comment by djc** [comment]
Looks good so far! Can you make it into a PR? I'd like to update `demo-rp` to make sure  can test this properly before it's merged.

**Comment by onli** [comment]
Sure. PR: https://github.com/portier/portier-broker/pull/13. And yes, this needs testing before the merge, I had no proper environment to do so.

**Comment by stephank** [comment]
This can be closed now?

**Comment by onli** [comment]
Yes. If not re-open.
