### ISSUE TITLE
Check handling of GMail address variants

### ISSUE THREAD

**Issue by djc** [portier/portier-broker#11]
With dots and pluses. Ideally, it should not canonicalize?

**Comment by callahad** [comment]
For gmail, we should normalize. Here's what we did in Persona: https://github.com/mozilla/persona-gmail-bridge/blob/master/lib/email.js

There are some gross things in there that we could have avoided with more mature libraries for parsing email addresses, but it worked well enough.

**Comment by callahad** [comment]
(Meaning, we should canonicalize in that manner to see if there's a match between user input and federated return value. if so, we should then return to the RP an identical string to the user's input)

**Comment by djc** [comment]
Right. This means changing the code that compares the JWT subject and the auth request email address to use a comparison function that canonicalizes email addresses.

**Comment by skorokithakis** [comment]
This seems simple enough that I can give it a go, I'll try it tonight and see how far I get.

**Comment by djc** [comment]
@skorokithakis awesome! Let me know if you run into trouble, I'm happy to assist.

**Comment by skorokithakis** [comment]
@djc Will do, thanks!
