### ISSUE TITLE
Implement "dummy" SMTP provider

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#115]
For local testing, I'd love to just dump emails to my console instead of actually sending them.

**Comment by onli** [comment]
I actually tested one for that, https://mailcatcher.me/, not integrated in the broker but as an external system. It did not work as the broker was dying with an error message about not having external access (or something similar) when trying to send the email to it. As that came from rusts mail internals I gave up on that point – but it still might be a good starting point, or an external solution we should just get to work.

**Comment by callahad** [comment]
See: https://github.com/portier/portier.github.io/pull/27

**Comment by callahad** [comment]
Woah, Mailcatcher looks cool.

**Comment by stephank** [comment]
Or [MailHog](https://github.com/mailhog/MailHog)

**Comment by onli** [comment]
So, I tried mailcatcher again. Configured like this:

```[smtp]
# Display name for confirmation emails - Default: "Portier"
from_name = "Portier"
# Sender address for confirmation emails - Default: (none)
from_address = "onli@Fallout"
# Outgoing mailserver address - Default: (none)
server = "smtp://localhost:1025"```
I also tried with 127.0.0.1. This is the error message:

```ERROR:iron::iron: Error handling:
Request {
    url: Url { generic_url: "http://localhost:3335/auth?scope=openid+email&response_type=id_token&nonce=d4a4f49c2ce04486a052c3c090d68cc8&response_mode=form_post&client_id=https%3A%2F%2Fportier-demo.herokuapp.com&login_hint=onli%40paskuda.biz&redirect_uri=https%3A%2F%2Fportier-demo.herokuapp.com%2Fverify" }
    method: Get
    remote_addr: V4(127.0.0.1:40070)
    local_addr: V4(127.0.0.1:3335)
}
Error was: Mail(Io(Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: Name or service not known") }) }))```

Doing some very profiessionial println!-debug, I now know that `let mut builder = SmtpTransportBuilder::new(app.smtp_server.as_str())?;` is the problematic line. Going even further down, I now know that `SmtpTransportBuilder::new` is the problematic part, as `app.smtp_server.as_str()` correctly prints as "smtp://localhost:1025". Which is the right value.

Don't know how to proceed. Someone of you familiar enough with lettre to know what is going wrong here? Or am I just missing something obvious?

**Comment by callahad** [comment]
Digging into the Lettre source, looks like it tries to call `std::net::to_socket_addrs` on the input, which eventually calls out to libc's `getaddrinfo`, which is where the "Name or service not known" error comes in... so it's not parsing your smtp server address correctly.

...try setting it to `localhost:1025` instead of `smtp://localhost:1025` and see what happens.

**Comment by onli** [comment]
> ...try setting it to localhost:1025 instead of smtp://localhost:1025 and see what happens.

That went a bit further, but then died when trying to send the email with

```
ERROR:iron::iron: Error handling:
Request {
    url: Url { generic_url: "http://localhost:3335/auth?response_type=id_token&redirect_uri=https%3A%2F%2Fportier-demo.angrybytes.com%2Fverify&response_mode=form_post&client_id=https%3A%2F%2Fportier-demo.angrybytes.com&login_hint=onli%40paskuda.biz&scope=openid+email&nonce=fd7eb30fb9b44861943ad9d304c5fdcb" }
    method: Get
    remote_addr: V4(127.0.0.1:54936)
    local_addr: V4(127.0.0.1:3335)
}
Error was: Mail(Io(Error { repr: Os { code: 111, message: "Connection refused" } }))
```

Which made me try `127.0.0.1:1025`, and that works! :) I could see the email in the mailcatcher web interface. 

I should add a line to the Readme, right? Will support like this for mailcatcher be enough to close this issue?

**Comment by callahad** [comment]
Yep! An update to the README mentioning MailHog and MailCatcher would be Good Enough for me :)

**Comment by onli** [comment]
Finally came around to write a few lines in the Readme. Please greenlight https://github.com/portier/portier-broker/commit/281d23a513b34eb451a15c4a9aa7ef832e2bd774

**Comment by stephank** [comment]
Oh hey, we can close this with #131 \o/
