### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#12]
The Broker needs a README that explains:

- Its exposed API surface (HTTP routes and methods)
- How to interact with it (which will likely form the basis of a future, general Using Portier doc on the main site)
- How to develop it locally
- How to deploy it in production

I'd especially love it if the document discussed deploying on Heroku or a similar PaaS's free tier, to facilitate hobbyists who want to self-host.

**Comment by callahad** [comment]
You can probably crib a lot of this from the README for my final prototype, at https://github.com/callahad/authbackend/blob/oidc-wip/README.md

**Comment by djc** [comment]
I'm not sure what the goals are for your first two points, but in my mind these are better off in another document. The former sounds like protocol documentation (e.g. https://github.com/portier/portier-broker/blob/master/protocol.md), which should be separated from the implementation. The second could be more of an implementer's guide, but I don't think it should bind strongly to this implementation.

**Comment by djc** [comment]
Please review what's there and let me know what you think.

**Comment by callahad** [comment]
Readme looks fantastic.

Feel free to skip the first -- I just like knowing what HTTP endpoints are exposed on things. Especially since stuff like the SMTP and Famous IdP return paths will be implementation specific.

Agree about the second being more general, and better off in a second document.

**Comment by djc** [comment]
Going to close this for now.
