### ISSUE TITLE
Portier Demo Not Working with Internet Explorer 11 / win7 (NL)

### ISSUE THREAD

**Issue by dickschrauwen** [portier/portier-broker#122]
CONFIRM-step not working in IE11/WIN7

(1) I downloaded 'https://github.com/portier/demo-rp' and installed it under windows 7 in 'C:\proj-new\websites\_PORTIER_TST\' 
(2) Got it running with:
```
# WIN7(64) Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32 
$> cd C:\proj-new\websites\_PORTIER_TST
$> python -m venv ./venv 
$> .\venv\Scripts\pip install -r requirements.txt
$> .\venv\Scripts\python .\server.py
# http://localhost:8000
```
Everything works nicely in  Chrome (NL, Versie 54.0.2840.99 m)
Did some testing with several gmail, yahoo and hotmail email-accounts.  Excellent!

However with IE11 (NL) I ran into a problem. IE stalls in the 'forwarding/confirm' step:
```
- https://broker.portier.io/confirm?session=L7gADlsA2SqkyAZ8NW54IHEYGjBaxTQbTayH47cOpWI&code=3dxhds+mar5ew+ 
- https://broker.portier.io/confirm?session=LGDQYAaHQif8_HVqsOgLUm2L9UUPrdQfbkRGPVPktDE&code=ns4o7wiq5smh
```
Discussion at:
https://groups.google.com/forum/#!topic/portier/FQHU8PDxy9g

**Comment by onli** [comment]
(I marked it as blocker because we at least need to know why that fails. IE11 is too big to ignore.)

**Comment by onli** [comment]
Removed blocker as IE11 was shown to work in general

**Comment by stephank** [comment]
Hope you don't mind if I close this, because it hasn't seen much activity, and I'm personally stumped by what's going on here.

I created #204 for whoever wants to improve the Windows testing situation.
