### ISSUE TITLE
Not receiving confirmation emails

### ISSUE THREAD

**Issue by dickschrauwen** [portier/portier-broker#128]
I'm not receiving confirmation emails. Nor from my flask site, nor from the online demo, nor from the local demo app.
```
- http://ikrik.com/en/login
- https://portier-demo.herokuapp.com/ 
- https://github.com/portier/demo-rp 
```
Something wrong with the mailserver?

**Comment by callahad** [comment]
Digging into our logs with Mailgun, I see:

> Server response: 550 550 OU-001 (SNT004-MC11F3) Unfortunately, messages from 104.130.122.18 weren't sent. Please contact your Internet service provider since part of their network is on our block list. You can also refer your provider to http://mail.live.com/mail/troubleshooting.aspx#errors.

From that URL, it looks like 550 OU-001 is:

> Mail rejected by Outlook.com for policy reasons. If you are not an email/network admin please contact your Email/Internet Service Provider for help. For more information about this block and to request removal please go to: http://www.spamhaus.org.

Querying the Spamhouse blocklists indicates that our shared Mailgun IP, 104.130.122.18, was recently flagged in the SBL advisory list under [SBL326364](https://www.spamhaus.org/sbl/query/SBL326364).

I've opened a ticket with Spamhaus asking them to investigate this and request delisting. Leasing a dedicated IP from Mailgun would theoretically solve this, but at $59/month, it's currently a bit expensive for this project.

**Comment by callahad** [comment]
The Mailgun support ticket is number 391230.

According to [Mailgun's documentation](https://help.mailgun.com/hc/en-us/articles/203446070-What-do-I-do-if-I-m-on-a-blacklist-), their standard procedure is to move accounts to a new IP while they resolve the blocklist issue, so I'd expect this to be addressed relatively quickly.

**Comment by callahad** [comment]
This should be resolved -- @dickschrauwen please verify on your end :)

**Comment by dickschrauwen** [comment]
@callahad 
Logged in (Log out)
with: Portier
as: dickschrauwen@hotmail.com
So, it's working
http//ikrik.com/en/login
Thanx

**Comment by callahad** [comment]
Closing as resolved - haven't seen any similar issues in the logs over the last week
