### ISSUE TITLE
Can't install under win7

### ISSUE THREAD

**Issue by dickschrauwen** [portier/portier-broker#129]
Did try several times to installl portier-broker on win7 prof (sp1).  
Installed
- visualcppbuildtools_full.exe (win, 14, 2015)
For folder-tree, see: http://pytrain.nl/MVS14-tree.txt

- rustup-init.exe 
(win: x86_64-pc-windows-msvc	✓	✓	✓	64-bit MSVC (Windows 7+))
(C:\proj-new\portier-broker>rustc --version => rustc 1.14.0 (e8a012324 2016-12-16)

Installation chokes on: 
- Compiling openssl-sys v0.7.17

====== Output in CMD ======================
C:\proj-new\portier-broker>cargo install portier_broker

    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling sha1 v0.2.0
   Compiling route-recognizer v0.1.11
   Compiling libc v0.2.19
   Compiling httparse v1.2.1
   Compiling typeable v0.1.2
   Compiling bufstream v0.1.2
   Compiling log v0.3.6
   Compiling lazy_static v0.2.2
   Compiling utf8-ranges v0.1.3
   Compiling num-traits v0.1.36
   Compiling bitflags v0.7.0
   Compiling winapi v0.2.8
   Compiling language-tags v0.2.2
   Compiling lazy_static v0.1.16
   Compiling redis v0.7.1
   Compiling num_cpus v1.2.1
   Compiling modifier v0.1.0
   Compiling matches v0.1.4
   Compiling traitobject v0.0.3
   Compiling error v0.1.9
   Compiling unsafe-any v0.4.1
   Compiling typemap v0.3.3
   Compiling plugin v0.2.6
   Compiling unicode-bidi v0.2.4
   Compiling emailaddress v0.3.1
   Compiling serde v0.8.21
   Compiling quote v0.3.10
   Compiling semver v0.1.20
   Compiling rustc_version v0.1.7
   Compiling unicase v1.4.0
   Compiling itoa v0.1.1
   Compiling gcc v0.3.41
   Compiling openssl v0.7.14
   Compiling rust-crypto v0.2.36
   Compiling openssl-sys-extras v0.7.14
   Compiling num-integer v0.1.32
   Compiling num-iter v0.1.32
   Compiling num v0.1.36
   Compiling regex-syntax v0.3.9
   Compiling num_cpus v0.2.13
   Compiling pkg-config v0.3.8
   Compiling rustc-serialize v0.3.22
   Compiling openssl-sys v0.7.17
Build failed, waiting for other jobs to finish...
error: failed to compile `portier_broker v0.1.0`, intermediate artifacts can be
found at `C:\Users\DirkS\AppData\Local\Temp\cargo-install.wLwomyyaPkzq`

Caused by:
  failed to run custom build command for `openssl v0.7.14`
process didn't exit successfully: `C:\Users\DirkS\AppData\Local\Temp\cargo-insta
ll.wLwomyyaPkzq\release\build\openssl-5464f8f6e728c35a\build-script-build` (exit
 code: 101)
--- stdout
TARGET = Some("x86_64-pc-windows-msvc")
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("x86_64-pc-windows-msvc")
debug=false opt-level=3
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CC_x86_64-pc-windows-msvc = None
CC_x86_64_pc_windows_msvc = None
HOST_CC = None
CC = None
TARGET = Some("x86_64-pc-windows-msvc")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_x86_64-pc-windows-msvc = None
CFLAGS_x86_64_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
running: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\
\cl.exe" "/nologo" "/MD" "/FoC:\\Users\\DirkS\\AppData\\Local\\Temp\\cargo-insta
ll.wLwomyyaPkzq\\release\\build\\openssl-5464f8f6e728c35a\\out\\src\\c_helpers.o
" "/c" "src/c_helpers.c"
c_helpers.c
src/c_helpers.c(1): fatal error C1083: Cannot open include file: 'openssl/ssl.h'
: No such file or directory
ExitStatus(ExitStatus(2))

command did not execute successfully, got: exit code: 2

--- stderr
thread 'main' panicked at 'explicit panic', C:\Users\DirkS\.cargo\registry\src\g
ithub.com-1ecc6299db9ec823\gcc-0.3.41\src\lib.rs:1018
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by stephank** [comment]
It'd be awesome if we could support Windows! But I'm not sure if any of us even have a Windows dev machine available. If you can get it working, that'd be a great first step.

Locating OpenSSL is fun on Mac too. The `openssl` crate has some special instructions for Windows as well, which maybe you can try: https://github.com/sfackler/rust-openssl/blob/v0.7.14/README.md#windows

Situation may change, eventually, we we switch to 0.9 of the `openssl` crate, but that may be some ways off. It depends on Hyper and Iron upgrading, which are in turn waiting for the Tokio stack to make a first release.

**Comment by dickschrauwen** [comment]
@stephank 
I'm trying to install broker under Win7prof and WinServer2008r2. When it works out I'll report back the HowTo

**Comment by dickschrauwen** [comment]
@stephank 
I gave up on win7. Let's try on my dedicated server, see: http://portier.niceware.com
