### ISSUE TITLE
Post an example config file

### ISSUE THREAD

**Issue by colemickens** [portier/portier-broker#167]
I can't tell what's wrong. No matter what valid Redis URL I use, I just get failure to create the storage client. Added more info and it's because it's failing to parse the redis url.

`thread 'main' panicked at 'unable to instantiate new redis store: "error opening store connection: Redis URL did not parse (url=http://127.0.0.1:6379/)"', libcore/result.rs:945:5`

Same with `127.0.0.1:6379`, etc.

**Comment by stephank** [comment]
I suppose it would help if mentioned somewhere what a Redis URL looked like! Will have to add that.

So, [Redis URLs are standardized](https://www.iana.org/assignments/uri-schemes/prov/redis) but it's not very obvious to find documentation on it. They look like `redis://hostname/0`, where `0` is the database number to use. The port is optional if you use the default.

**Comment by onli** [comment]
Thanks! I ran into the same issue when setting up my test broker, but wasn;t sure whether I maybe just lack some common knowledge.
