### ISSUE TITLE
How verify the JWT in Rust?

### ISSUE THREAD

**Issue by greglearns** [portier/portier-broker#176]
What is the recommended way in Rust to verify the JWT that Portier sends?

I am currently accessing the RSA public components (`n` modulus, and `e` exponent) from `https://broker.portier.io/keys.json` but then what?

I'd like to use https://github.com/Keats/jsonwebtoken#rsa but `jsonwebtoken can only read DER encoded keys currently` and the other Rust JWT decoders all seem to have the same limitation.

Any ideas?

**Comment by jestarray** [comment]
@greglearns did you ever find out what to do? I'm going to need to do this eventually also.

**Comment by stephank** [comment]
I just published a first version of a Rust client. It's geared towards Tokio + Hyper for now: https://docs.rs/portier

Hope you don't mind if I close this issue now. Feel free to reopen and discuss further, but we can also continue with issues / PRs in the new repo at: https://github.com/portier/portier-rs
