### ISSUE TITLE
Portier does not validate scopes properly

### ISSUE THREAD

**Issue by colemickens** [portier/portier-broker#180]
Per the spec:

` Verify that a scope parameter is present and contains the openid scope value. (If no openid scope value is present, the request may still be a valid OAuth 2.0 request, but is not an OpenID Connect request.) `

Yet, I'm using this with Dex and I've configured `id_token` as the only scope and it's working.

**Comment by onli** [comment]
I'm not sure that validating `scope` is needed. We might not follow the spec to the letter there, but since we only have one flow that will happen later the broker should be fine just ignoring the scope parameter. Or am I misunderstanding/missing something, has this negative consequences?

**Comment by colemickens** [comment]
Does Portier Broker intend to be an OAuth2 provider beyong OIDC? If not, then I think `portier-broker` is fairly blatantly violating the OIDC specification.

**Comment by colemickens** [comment]
In practice, this leads to confusion in the OAuth/OIDC world in general. For example, I discovered this because Dex configuration that worked with Portier was failing when used with Okta. Turns out, it's because Okta expects the `openid` scope per the spec, whereas Portier was silently letting me get away with making an invalid request.

**Comment by onli** [comment]
Okay, then this should be fixed. If it's just "not following the spec to the letter", that doesn't matter much, but if it has consequences in practice there is no reason not to do it right?

Which flow are we talking about exactly? Did you use dex as a client to use portier as IdP, or did portier try to identify with Okta, with Okta being the IdP?

**Comment by colemickens** [comment]
>Did you use dex as a client to use portier as IdP

Yes. Dex acting as an IdP and brokering to other one of multiple backends. I had Portier working, and wanted to add Okta as a sibling. Rather than just taking Portier's config and changing the issuer, I had to go debug why Portier's config didn't work with Okta. Turns out, I was asking Portier for an invalid and incorrect scope, but it didn't mind.

To illustrate more clearly, you can see the commits and the comments change as I discovered this last night. If you look at the latest three commits here, you will see why I discovered this and found it a bit offputting: https://github.com/colemickens/dex-portier-demo/commits/master/dex.yaml

So the implicit flow with `Dex -> Portier` or `Dex -> Okta`. Nothing more complicated than that.

I view this as extremely minor, there's no loss of functionality due to the current behavior. This is something I can send a PR for but its not high on my list right now.

**Comment by onli** [comment]
Okay, great!

We designed Portier to follow the OIDC spec as far as seemed sound, but it was not a priority to get it 100% combatible, though it was kind of a stretch goal. I'm not even aware of people using proper OIDC clients so far instead of custom portier clients, so your work is definitely appreciated!

**Comment by stephank** [comment]
See: https://github.com/portier/portier-broker/pull/193

That PR makes it so `openid` is required, and `email` is optional, but provided in the id_token claims regardless. Any other unknown scopes result in an error.

That should be correct, right?
