### ISSUE TITLE
Problems configuring Google oauth

### ISSUE THREAD

**Issue by marianopw** [portier/portier-broker#182]
I have portier-broker working correctly on my server, but when using a gmail address it sends an email like it was a normal email address.
My google oauth token is configured on config.toml, but that doesn't seem to work, so i think this might be a problem with my google api console configuration.
Any hint on how this should be set up?
This is my current config:
![Screenshot from 2019-03-25 15-09-53](https://user-images.githubusercontent.com/13471075/54943468-1ca29980-4f10-11e9-9842-9008ce6030fb.png)

Login.automata.pw is the portier broker
dashboard.automata.pw is the login page
thanks!

**Comment by marianopw** [comment]
Ok, after a long time i came back to this issue and figured i had the wrong settings in both config.yaml and google services config.
In config.yaml i forgot to put declare the google section by adding `[google]` before my client ID (i just added the client_id).

Heres the correct way.
```
[google]
client_id = "yourclientid1208309128409hsih.apps.googleusercontent.com"
[providers."gmail.com"]
# Google OAuth API Client ID - Default: (none)
# Google OpenID Connect discovery URL - Default: "https://accounts.google.com/.well-known/openid-configuration"
discovery_url = "https://accounts.google.com/.well-known/openid-configuration"
# Google OpenID Connect id_token issuer domain - Default: "accounts.google.com"
issuer_domain = "accounts.google.com"
```
And in the google configuration, you need to set yourdomain.com/callback as your callback url, like this.

![Screenshot from 2019-06-02 20-52-05](https://user-images.githubusercontent.com/13471075/58768940-66df7100-8578-11e9-9a96-550d4295f260.png)

That's all. It's working fine now. Thank you for this awesome project!

**Comment by onli** [comment]
Thanks for reporting your solution! The config.yaml can be confusing.
