### ISSUE TITLE
Dot in email disappears when using gmail to login

### ISSUE THREAD

**Issue by andreas-ku** [portier/portier-broker#199]
When I am logging in with my Google email address (which contains a dot), the email address received by the client is missing that dot.

This can be reproduced on the demo website, but also when I was integrating portier via portier-node, so I assume it's an issue within the broker.

I created the same email address with another email provider and the issue was not showing up. It seems this only affects the login via Google.

**Comment by stephank** [comment]
Sorry about that. This is fixed in 0.3, but we still have to update the public broker. The issue with updating it is that the change is breaking, and we have to announce it. I will leave this bug open until we have it updated.

**Comment by andreas-ku** [comment]
No worries, thanks for the update @stephank !

**Comment by stephank** [comment]
This should now be fixed. The public broker has been upgraded to 0.3.2. :)
