### ISSUE TITLE
Enforce code style with rustfmt?

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#25]
Many of the comments on our pull requests are concerned with code style ([example](https://github.com/portier/portier-broker/pull/21#pullrequestreview-3865395)). Rather than rely on falliable humans for this, let's just use [rustfmt](https://github.com/rust-lang-nursery/rustfmt).

It's quite configurable, and we can [set up Travis](https://github.com/rust-lang-nursery/rustfmt#checking-style-on-a-ci-server) to ensure that PRs follow the code style.

**Comment by callahad** [comment]
I think we're blocked on rustfmt being nondeterministic (see: https://github.com/rust-lang-nursery/rustfmt/issues/1141 and https://github.com/portier/portier-broker/pull/26).

Most of the edits seem to settle down after a few runs, but until it's deterministic, we can't make rustfmt an automatic part of our CI.

We could still come up with reasonable settings, run rustfmt until we're happy, and manually commit those for now...

**Comment by djc** [comment]
Yeah, I like automating this more, although I'm definitely not so fond of some of rustfmt's defaults. If we can tweak it right, that would be great.

**Comment by stephank** [comment]
This has since been fixed, and the codebase follows the standard rustfmt style.
