### ISSUE TITLE
Allow for setting configuration and signing keys via environment variables

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#32]
The only sane way to deploy configuration on a PaaS like Heroku is using env vars. See also: https://12factor.net/config

We need some way to pass configuration into the Broker without requiring a `config.json` and `key.pem` file on disk.

I'm particularly fond of a cascade of:

    App-Specific Env Vars > Common Env Vars > Config Files > Defaults

The demo rp is configured in this way: [settings.py](https://github.com/portier/demo-rp/blob/d693c2adcce2e4d2f53c1ea0ee9a33f636dd6ae9/settings.py), [README.rst#Configuration](https://github.com/portier/demo-rp/blob/d693c2adcce2e4d2f53c1ea0ee9a33f636dd6ae9/README.rst#configuration)

**Comment by djc** [comment]
I read the 12factor thing, but I can't believe that the best solution for this problem space is to have 12 or 15 different environment variables to convey each of these values separately. And I presume the solution is also not having environment variables with JSON or some other way of having multiple actual values in there.

**Comment by callahad** [comment]
For traditional servers or local testing, configuration files are still available, but for PaaS and container-based workflows, environment variables work extremely well and genuinely solve real problems -- they're the only thing that's feasible when you can't expect your local disk to be persistent.

It's also extremely important that we choose reasonable defaults, or try to infer as much as possible from the surrounding environment. For example, the [Demo RP](https://github.com/portier/demo-rp) has six available envvars, but I don't have to set any for local development, and I only have to set `DEMO_SECRET` for production deployments.

For the Broker, I suspect we'll only need to manually set `base_url`, `keys`, `sender`, the gmail `client_id`, and the gmail `secret`. Five variables isn't so bad.

It's also much simpler administratively: the variables persist across deployments, so we don't need to worry about sharing a private config file between us and carefully only checking it into a separate, private deployment branch of the repo. Instead, we just worry about the code, and the infrastructure worries about the configuration.

**Comment by stephank** [comment]
Even `keys` is something we can generate for testing, with a big fat warning.

I haven't looked into it, but maybe you can sit inbetween `serde` and `serde_json`, implement this as a custom deserializer?

**Comment by buro9** [comment]
Every setting should be settable via an ENV.

It's the only way to really manage process config and process secrets securely, and it's the preferred way in any container environment, i.e. Mesos + Marathon.

The advantage is typically that the ENV isn't going to appear within a `ps -aux` (args will), and the ENVs are protected as part of the session, which implicitly are going to be the equivalent of a well-secured config file but without explicitly requiring that locking down of the config file.

At the very least, anything that could be considered to be a secret should be settable via an ENV.

**Comment by stephank** [comment]
With #50 merged, I ticked off a couple of your items @callahad, but I'm not sure you want to close this yet. Though the MVP Blocker tag can probably go now?

**Comment by callahad** [comment]
One final task: we should probably make it possible to specify a PEM-encoded key as a string in an env var. Supporting that should be fairly straightforward.

**Comment by callahad** [comment]
Done!
