### ISSUE TITLE
Move onto Heroku

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#33]
We need to be on some kind of managed, horizontally-scalable PaaS before launch.

**Comment by djc** [comment]
Why is this an MVP blocker?

**Comment by callahad** [comment]
For easy monitoring, administration, billing, and scaling, as well as making operational tasks available to those of us without root on xavamedia.nl :)

Scenarios:

- We need to deploy another sever or two: it's literally just dragging a slider.
- We need to monitor logs: `heroku logs -t`.
- Redis somehow turns into a bottleneck: point-and-click to a beefier, paid plan.
- We need to deploy a hotfix: we can configure Heroku to automatically deploy whenever we merge to `master` here.
- We want to centralize billing and credentials for things like outbound emails: PostMark, SendGrid, and others federate into Heroku.

**Comment by callahad** [comment]
Done!
