### ISSUE TITLE
Sign our emails with DKIM, good SPF records, and other best practices

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#34]
It's important that the mail we send hits inboxes. Part of that is having appropriate SPF records and signing the outgoing mail with DKIM, monitoring delivery / bounce rates, etc.

Providers like Postmark, SendGrid, or Mailgun are great for this.

**Comment by buro9** [comment]
I've submitted a ticket to SendGrid to ask whether they have any non-profit plans.

I have recently moved all of my own email to SendGrid after trying each of Postmark, Mailgun and Mailjet for a month at a time. Prices are all comparable, but the DKIM and SPF support by SendGrid was really good and I found it easier to build reputation on their platform as things like Mailgun throttle email sending whilst you are new to the platform... and for authentication timeliness is important.

**Comment by splewako** [comment]
It would be great if outgoing mail servers could have certificates installed.

**Comment by callahad** [comment]
@splewako+, but we need to move to a server with those certs :) This is more of an ops bug than an code bug necessarily.

**Comment by callahad** [comment]
I've set up Sendgrid on Heroku. This is done.
