### ISSUE TITLE
Send reasonable security headers, including CSP, HSTS, and possibly HPKP

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#38]
References:
- https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#tab=Headers
- https://observatory.mozilla.org/

**Comment by djc** [comment]
Currently the broker always runs behind a proxy, so I'm not sure if it makes sense to implement these in the broker itself or in the proxy?

**Comment by callahad** [comment]
Since CSP tends to be rather deeply coupled to application structure and logic, I'm confident that one should at least be coming from the application.

**Comment by buro9** [comment]
That and SRI https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

But it's a pain to maintain those.

**Comment by callahad** [comment]
SRI is hard mode. We should aim for it, but not until the rest of our ducks are in a row. :)
