### ISSUE TITLE
Send Cache-Control header in response

### ISSUE THREAD

**Issue by stephank** [portier/portier-broker#41]
We should add the `Cache-Control` headers to our responses.
- Login routes: `no-cache, no-store`.
- Discovery document and other static resources: `public, max-age=86400` (1 day)
- Keys document should be `public`, with a configurable age. This depends on how often keys are rotated.
- `/.well-known`, probably `no-cache`?

**Comment by djc** [comment]
Also, ETags and Last-Modified headers?

**Comment by stephank** [comment]
Working on this in the `featureCacheHeaders` branch. So far, sending Cache-Control for discovery, keys and static files. Unfortunately, the staticfile crate doesn't send ETags, but does send Last-Modified.

**Comment by callahad** [comment]
Is there an upstream bug on the staticfile crate for ETag support that we can track?

**Comment by callahad** [comment]
(I didn't see one)

**Comment by stephank** [comment]
Just went and created a small PR: https://github.com/iron/staticfile/pull/92

Let's see how they find it! :)
