### ISSUE TITLE
SIG{TERM,INT} handlers

### ISSUE THREAD

**Issue by jimdigriz** [portier/portier-broker#414]
When you get a chance, can you add `SIG{TERM,INT}` handlers to the broker to shut it down (exit code 0).

This would allow Ctrl-C and when running as PID 1 (eg. inside Docker) for it to shutdown as most would expect.

**Comment by stephank** [comment]
This was released as 0.6.0. 🙂

**Comment by jimdigriz** [comment]
Yes, I saw and deployed immediately into production on Friday :) Thanks!
