### ISSUE TITLE
Allow setting SMTP credentials

### ISSUE THREAD

**Issue by stephank** [portier/portier-broker#43]
We currently only support unauthenticated SMTP connections, which is fine if access control is done some other way. (E.g. mailserver only listens on localhost, or is strictly firewalled.)

For AWS SES or other cloud mail services, we need to provide credentials and support STARTTLS.

**Comment by callahad** [comment]
I think this blocks #33?

**Comment by stephank** [comment]
Should be able to fix this soon, anyway. I have a branch with a credentials implementation I'm currently testing, waiting on Amazon support to take us out of the SES sandbox.

As for STARTTLS, it's currently ugly to make configurable. Lettre has a `SecurityLevel` enum that's not clone or copy, so we can't store it in config. Probably should try to get a patch upstream.

But the current default is 'opportunistic', so it'll use STARTTLS if available anyway.

**Comment by stephank** [comment]
Lettre master fixes the SecurityLevel irk, so we should be able to complete this on their next release (0.6.2, 0.7.0, or otherwise).

I think #46 should be sufficient to unblock Heroku, though?

**Comment by callahad** [comment]
This is done -- closing :)
