### ISSUE TITLE
Measure (and increase) test coverage

### ISSUE THREAD

**Issue by djc** [portier/portier-broker#5]

**Comment by callahad** [comment]
We want to make sure we don't panic on invalid input data, a la #28

**Comment by callahad** [comment]
Potentially helpful blog post on generating code coverage reports for Rust: http://sunjay.ca/2016/07/25/rust-code-coverage

**Comment by callahad** [comment]
Also this: https://users.rust-lang.org/t/tutorial-how-to-collect-test-coverages-for-rust-project/650/33
