### ISSUE TITLE
Browser prefetch can trigger `/auth`

### ISSUE THREAD

**Issue by stephank** [portier/portier-broker#53]
This is, of course, a direct result of: https://github.com/portier/portier-broker/pull/16

But we need that for spec compliance. I'm hoping there's a way to be smart about this and detect prefetches.

**Comment by callahad** [comment]
What would initiate the prefetch? What negative impact would it have?

(Is it just the appearance of the URL in the user's browser history? Since we're not exposing links to `/auth` anywhere...)

**Comment by stephank** [comment]
History, yes. It's appearing more and more often in addressbar completion.

**Comment by callahad** [comment]
Ugh. We could probably mitigate this on the RP side, but it'd be ugly.

Right now we have a form that POSTs the email address to the backend, which then redirects the user to the broker.

If we could find a way to POST directly to the broker, problem solved. That might look like XHR'ing the email address to the backend to get a nonce, writing the nonce into a hidden field on the page, and then submitting the form.

...not sure I like that much, either.

**Comment by stephank** [comment]
One possible solution I'm eyeballing is to have the broker redirect from email `/auth` to a  `/confirm-email` or similar. Maybe that'll hide the `/auth` URLs from history, but I haven't investigated yet.

**Comment by stephank** [comment]
Redirects don't work, apparently. Tried both 301 and 303, but Chrome shows both in history, still.

One possible solution might be add JS inbetween, and check this: https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API

**Comment by stephank** [comment]
Closing this, as I haven't seen it since.
