### ISSUE TITLE
Reconsider degree of configurability

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#59]
Do we _really_ need:
- `crypto.token_ttl`
- `redis.session_ttl`
- `redis.cache_ttl`
- `redis.cache_max_doc_size`

The TTLs all seem like things we can/should take an opinionated stance on, and the max document size in the Redis cache seems of questionable utility.

**Comment by stephank** [comment]
I think these values may prove useful in testing in the future, so I believe we should keep them around. I hope we've since adequately documented these in `config.toml.dist` as having sensible defaults.
