### ISSUE TITLE
Enable continuous delivery on Heroku?

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#64]
I'd like it if any merge to `master` automatically deployed to Heroku. I've set this up for the Demo RP, and it works great.

Environment variables persist across deployments and Redis is kept separate, so there's no other state we need to worry about preserving.

**Comment by stephank** [comment]
Down the road, we probably want a `dev` branch where we land merges before making a release. (Or flip the situation around and deploy from a `release` branch, but I like that a bit less.)

**Comment by stephank** [comment]
We now have continuous deployment of `master` to staging, for both broker and demo.
