### ISSUE TITLE
We need an icon

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#67]
Both for favicon and Google auth screen reasons. Compare:

![screenshot from 2016-10-26 16-19-13](https://cloud.githubusercontent.com/assets/24193/19745802/f6d02d26-9b98-11e6-90d7-4860f4e6b7aa.png)

---

![screenshot from 2016-10-26 16-23-13](https://cloud.githubusercontent.com/assets/24193/19745804/fae324d6-9b98-11e6-8c2d-4a3b4077df97.png)

**Comment by onli** [comment]
Possible placeholders:

![portier](https://cloud.githubusercontent.com/assets/900380/19803402/c4ef1576-9d08-11e6-9665-318d7b31db86.png)

![portier_2](https://cloud.githubusercontent.com/assets/900380/19803457/13495e0c-9d09-11e6-8ce9-f6e1747a1d51.png)

**Comment by callahad** [comment]
I like the direction the top one is going. I wonder if it's worth approaching something like [FairPixels](http://www.fairpixels.co/), who recently [ran a contest](https://news.ycombinator.com/item?id=12372118) for free logo design for open source projects, or perhaps something more mass-market like [99designs](https://99designs.com/). Though I do find that kind of spec work a bit unethical...

I could also try to find a student at my local [art school](http://mcad.edu/)?

Thinking this is less urgent than before -- if we want Portier to be infrastructure, maybe it's best to not have a logo on the Google consent screen?

**Comment by stephank** [comment]
It'd be nice if we could have *something* in the Google consent screen. Perhaps the middle road is to make have our logo a generic login logo, but still recognisable as Portier. If that's possible, we won't surprise users at the consent screen. Full versions of the logo can then still have 'Portier' subtext, much like these do.

**Comment by onli** [comment]
![portier-logo](https://cloud.githubusercontent.com/assets/900380/19849343/04c568fc-9f53-11e6-8acb-e9a3c8af4205.png)

Still needs some work, the P and the ortier don't have exactly the same line width, and maybe the ortier should use ligatures. But I think the idea could work, the Icon-part of the P is the font-awesome icon for login, and this could then be used where we don't want full branding.

**Comment by onli** [comment]
No feedback? Well, that's normally a sign no one like it 😆 

I really thought the sign in symbol merged into the P could work. No agreement there? Shall we find another way to get a logo? The local art school still an option? I had contact with a logo designer who built https://www.pc-kombo.de/logo.png for me, which I found to be at least acceptable. We could contract him, or someone like him.

I actually think we should have a logo. Yes, there is the argument that we do not want to create a product, but a logo is just helpful when writing articles about portier or when creating listings like on https://alternativeto.net/software/portier/.

**Comment by callahad** [comment]
/me looks at feet, shuffles back and forth.

I don't love it, yet. I wonder if we could get by with just a simple wordmark in an interesting typeface for now, until we can investigate Actual Designers? Maybe [one of these](https://fonts.google.com/selection?subset=latin&category=Monospace&selection.family=Medula+One|Neuton|Overlock+SC|Poiret+One&sort=popularity) from Google Fonts?

![screenshot from 2017-01-03 23-49-02](https://cloud.githubusercontent.com/assets/24193/21632787/3ec6e212-d20f-11e6-9aef-2d6d23999e1d.png)


(Other input definitely welcome!)

**Comment by onli** [comment]
The last font is Poiret One, and I like it, despite the wide o. Especially for a logo it could work fine. It is under the OFL, http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL_web, which allows that usage.

We would still need a single-letter or small icon though, I don't think we can show something that wide in all places (though the consent screen is gone now, if I understood the effect of #86 correctly). And even if it is just a favicon.

On logodust, there are 2-3 icons that could also work. This one for example:

![logo35](https://cloud.githubusercontent.com/assets/900380/22519440/8b1a6e4c-e8b0-11e6-99e2-e7203ae2fbc5.png)

Not sure how widely used those logos are, but it fits: It is a P, you can interpret it as protecting access, and it can even stand for a very specific kind of portier.

**Comment by feluxe** [comment]
Something like this maybe?
![portier](https://user-images.githubusercontent.com/6545589/32701031-f8c149a4-c7ce-11e7-88eb-f0baa000524c.png)


The idea was to merge the P of 'P'ortier with a key icon.

**Comment by onli** [comment]
I like it. @stephank, is it okay for you?

**Comment by stephank** [comment]
I really like that one! The version you provided has some artefacts in the background, it looks like?

Do you have it in SVG format? And could you tell us what font you used for the P, if any? Might be useful if we ever need to match it elsewhere. :)

**Comment by feluxe** [comment]
Cool! I'm glad you like it :)

So far it's just a sketch I made with Gimp. I only have it as a bitmap. But if you like to use it, I could make a SVG from it with InkScape.

The 'P' is it's own form, no font. You are right, it would be good to have a dedicated font.

How about something like this? (sketch based on 'aakar' font)
![portier2_icon](https://user-images.githubusercontent.com/6545589/32914500-0cd2bd70-cb16-11e7-978b-793c71fd7bf9.png)

Could be used something like this, when written out:

![portier2_text](https://user-images.githubusercontent.com/6545589/32914525-211fde98-cb16-11e7-9c52-f1c58e86ba54.png)

**Comment by onli** [comment]
I think multiple of those suggestions would work just fine. Nice work :) 

I like the last one the most, surprisingly. We can also have both, still use the orange icon as a standalone icon (for favicons for example) and when it has to be written out in a title use the black/white version, though the black and white P in a circle would probably work equally well for standalone icons... 

Could you maybe transform the last black and white version and one colored circled P into an SVG?

**Comment by feluxe** [comment]
Thanks! 

> Could you maybe transform the last black and white version and one colored circled P into an SVG?

I could give it a try, but before I do, it's important that all agree on a final-ish version, because I think it'll be quite an amount of work to make a SVG out of it. I'm not a vector-graphic ninja ;) It's much easier to do the prototyping on a bitmap.

My suggestion:
You agree on a version. I make a clean highres bitmap out of it and provide png's in multiple sizes. You test the png's in *"production"*, then we see if more changes are needed or not. If more changes are needed I can easily adjust the bitmap. If both, the icon and the logo look fine in *"production"*, I provide SVG's.

> I like the last one the most, surprisingly. We can also have both, still use the orange icon as a standalone icon (for favicons for example) and when it has to be written out in a title use the black/white version, though the black and white P in a circle would probably work equally well for standalone icons...

That's exactly what I thought. I would go with three versions:

* logo (written out)
* icon (filled circle)
* icon (empty outlined circle)

and then make different color versions for them:

* logo black on transparent
* logo white on transparent

* icon (filled circle) white on orange
* icon (filled circle) white on black
* icon (filled circle) black on white
* icon (empty outlined circle) orange on transparent
* icon (empty outlined circle) black on transparent
* icon (empty outlined circle) white on transparent

That would make a logo/icon for every possible situation ;)

**Comment by onli** [comment]
That sounds great. Let's hear what @stephank thinks, but I assume it will no problem finding something we three agree on.

**Comment by stephank** [comment]
Definitely agree with everything said here. For the full logo, the last one feels right because everything is on the same baseline.

The plan you outlined sounds great, @feluxe! 👍 SVGs are more nice-to-have, if we already have all those variants in high-res. :)

**Comment by skorokithakis** [comment]
To make an SVG, you can trace the bitmap you already have. It wouldn't look half bad, and you can clean it up later if you want. I could give it a shot.

**Comment by onli** [comment]
I created an SVG version (with some slight modifications) of @feluxe logo at https://gist.github.com/onli/447519c605dbdc3b69f8c66aec708ca7. Font is taken from https://github.com/kartikm/fonts-aakar (GPL licensed, which is okay).

Exported looks like this:

![portier_logo_feluxe_recreated](https://user-images.githubusercontent.com/900380/126667967-b1097fe2-aa7b-4c4b-a78e-5755b10dfa9a.png)

Core differences:

 * P is a modified P of the aakaar font
 * P has the same size as the rest of the text 
 * Some kerning fixes based on visual impression (maybe the r and t are still too close?)
 * The circle is drawn a bit different

We could use that as long logo, and the circled P as image logo. Maybe with a speck of color, but that's completely optional. I'm fine with keeping it black.

**Comment by onli** [comment]
Standalone P:

SVG Gist: https://gist.github.com/onli/13dc10fc0e0410be5d2a52327f66e9da

![portier_p](https://user-images.githubusercontent.com/900380/126669870-e636f89b-f94a-4925-9dbf-78fcd0907411.png)

**Comment by onli** [comment]
We do have an icon for a while now, I think we can safely close here :)
