### ISSUE TITLE
trim whitespace on paste of code

### ISSUE THREAD

**Issue by jimdigriz** [portier/portier-broker#758]
Could you add a [`onpaste`](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event) to [`tmpl/confirm_email.mustache`](https://github.com/portier/portier-broker/blob/main/tmpl/confirm_email.mustache) to handle lesser {web,e}mail clients that seem to place sometimes considerable whitespace before the confirmation code?

Though you do remove all whitespace in [`src/bridges/email.rs:confirmation`](https://github.com/portier/portier-broker/blob/main/src/bridges/email.rs) I am seeing the problem before we get to the endpoint due to the text input field having a limit of 20 and it submits a truncated confirmation instead.

"Why does this happen, surely 20 is enough?", you may ask, and it is true and it is a good question...but it turns out software hates all people...

What I have observed:

1. the code emailed to me is `123456 abcdef` (12 characters + 1 space)
2. I double click on the code to paste it in to the confirmation box
3. what is actually pasted is N leading spaces, I see mostly 1 which works fine in the 20 character limit but I am able to regularly have it paste in 8 leading whitespace characters which results in the trailing `f` being truncated/ignored
     * you can see this yourself if you press the space bar eight times before pasting in the code
     * the HTML in the email template is just the paragraph element wrapping the code so it seemingly is not something I can fix there: ![image](https://github.com/portier/portier-broker/assets/2567406/f2f8ea4f-f1fc-4362-9ef6-33ac62aa0192)

Maybe we could include something like:
```
<script>
 document.querySelector("input[name='code']").addEventListener("paste", function(e) {
  e.preventDefault();
  this.value = e.clipboardData.getData("text/plain").trim()
 });
</script>
```

The reason I am proposing the `onpaste` hook is:
1. users may post trim the whitespace manually after seeing it pasted incorrectly but they are unlikely to notice a single character being trimmed off
2. the user can still pound the enter key blindly :)
3. I suspect we do not want to avoid the problem by just bumping the limit to something higher than 20, though this could work too? Maybe do both?

**Comment by stephank** [comment]
Fixed in #781
