### ISSUE TITLE
make failed logins less brutal to improve UX

### ISSUE THREAD

**Issue by jimdigriz** [portier/portier-broker#762]
On a failed login, the Portier broker deletes the session preventing further attempts to log in with that session. It would be helpful to be able to configure the broker to instead only delete the session on a successful login; as well as the after a deadline has expired as it already does.

From our experience, the current behaviour hurts the UX as we see regularly people failing to log in for legitimate and expected reasons but (we assume) very few attempts to brute for the code; which for most is moot and prevented by any CSRF protection (ie. a cookie) in the resource provider.

This is described in https://github.com/portier/portier-broker/issues/670#issuecomment-1558749446 and followed up by https://github.com/portier/portier-broker/issues/670#issuecomment-1568521993

Common reasons for a failed login:
1. different browsing context; resource provider is open in one browser (or incognito window) but when opening the link in the email it pops open another browser (or non-incognito)
2. login code is mistyped of [pasted incorrectly](https://github.com/portier/portier-broker/issues/758)

This problem is potentially exasperated by the rate limiter as our users get at least confused and then re-attempt fresh logins which also fail as they are still incorrectly doing something or other.

**Comment by jimdigriz** [comment]
It may be worth also exploring (maybe behind an option if it feels icky) if a given email address is trying to log into the same `client_id` and there currently is an outstanding session for that, to just resend the same code to the user; if say there is at least a few minutes left on the clock or maybe if it was within N minutes of the original one having being sent.

**Comment by stephank** [comment]
v0.12.1 now allows retries. We didn't really delete the session, you could just navigate back and retry on old versions too, I believe. Now there's just some UI for it.

There's not yet an option to resend the email. Might still be useful to have?

We could also add a max tries option to further lock down brute forcing, though I also wonder if that really adds much in terms of security.

**Comment by jimdigriz** [comment]
> v0.12.1 now allows retries

This is great, thanks. I'll try to roll it out and get it exercised by the masses for the New Year.

> We didn't really delete the session, you could just navigate back and retry on old versions too

Maybe what I observed was the session cookie set by our *application* (JupyterHub for one of our use cases) for CSRF protection being changed after the user attempts another login; which is expected and mostly non-recoverable.

> There's not yet an option to resend the email. Might still be useful to have?

I would recommend not doing so. Sort of similar to when people hammer the 'Print' button, all it does is queue up a bazillion jobs once the actual problem is resolved :)

> We could also add a max tries option to further lock down brute forcing, though I also wonder if that really adds much in terms of security.

Might be useful, 36**8 combinations in a 15 minute(?) window probably keeps you mostly safe I suspect.

Thanks again! Portier is really a wonderful software project, a force for good! :)
