### ISSUE TITLE
Bump DMARC policy to p=quarantine or p=reject

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#77]
Right now our DMARC record is set to p=none. It looks like it's working, and I can't imagine anything else sending mail from our domain, so we should be able to bump it to a more restrictive policy soon.

Revisit in mid-November, once we have a few weeks of running the broker in production under our belts.

**Comment by stephank** [comment]
I've been slowly increasing the quarantine percentage, and last week had it on 100%. The reports all look fine, and all my own email forwards keep working. I've now change the policy from quarantine 100% to reject 100% and verified my forward is still working. So we can now close this!
