### ISSUE TITLE
Handle errors and return them to the RP if possible

### ISSUE THREAD

**Issue by djc** [portier/portier-broker#8]

**Comment by djc** [comment]
I think this means throwing some errors in the [AuthHandler](https://github.com/portier/portier-broker/blob/master/src/lib.rs.in#L136) if the required parameters (per OIDC Implicit Flow, see #10) are not passed in. Should probably be a 400 Bad Request with an HTML page showing a human-readable error.

**Comment by djc** [comment]
For errors in the processing where we have a non-expired login in the store, we should throw an error message to the RP's callback URL.

**Comment by stephank** [comment]
Should a discovery error of the upstream OpenID provider cause Portier to fall back to email verification?

(Not yet working on this, just a thought.)

**Comment by djc** [comment]
I think it depends on what stage of discovery it would happen.

There's a security aspect to this: if the email provider shows any signs of trying to implement "native" IdP process, it might mean that they want to require extra restrictions (like 2FA) on top of just email notification. Therefore, we should err on the side of caution, thus restricting access, if native verification seems to be supported in whatever way but ends up being broken.

**Comment by callahad** [comment]
I believe this is done. Please reopen / file a new bug if not.
