### ISSUE TITLE
Handle all unknown URLs by returning a 404

### ISSUE THREAD

**Issue by callahad** [portier/portier-broker#82]
Right now we panic. We shouldn't panic.

**Comment by stephank** [comment]
We don't panic, I think? The router just returns an Err. But the response is still a 404.

Do you have a specific URL that panics?

It might be nice to add some AfterMiddleware that converts Err(NoRoute) to Ok, though, just to keep our logs clean.

**Comment by callahad** [comment]
I swear I was seeing this on `GET /favicon.ico`, but not anymore. Oh well.
