### ISSUE TITLE
Translating to French

### ISSUE THREAD

**Issue by daniel-g-gagnon** [portier/portier-broker#902]
I produced a French translation but I get this error when trying to produce the .mo files:

```
$ msgfmt fr.po -o fr.mo
msgfmt: input file doesn't contain a header entry with a charset specification
```

My version of msgfmt is:

```
$ msgfmt --version
msgfmt (GNU gettext-tools) 0.22.5
```

The msgfmt.sh script at the root of the repo similarly breaks on every .po file.

If you help me fix this, I’m ready to send you a PR.

**Comment by stephank** [comment]
Sorry for the delay. I think b4e0cc4 should fix it, which is already on the `main` branch. You'll need to add a similar header to your translation file. Thanks for working on this! 🙂

**Comment by daniel-g-gagnon** [comment]
It fixed the problem, thanks.
