### ISSUE TITLE
Redirect url without trailing slash produces `redirect_uri does not match the original from the authorization request`

### ISSUE THREAD

**Issue by kurnevsky** [portier/portier-broker#915]
Hi. I'm getting the error `redirect_uri does not match the original from the authorization request` if I use `redirect_url` without path and trailing slash like `http://127.0.0.1:8082`. It works fine with slash like `http://127.0.0.1:8082/` or any path. It's not critical, but the cause wasn't obvious so probably worth fixing, so reporting it :)

**Comment by stephank** [comment]
Thanks for pointing this out. Will be in a release shortly. 👍

**Comment by stephank** [comment]
This is released in v0.12.1.
